package com.rd.db.dao;

import java.util.List;

import com.rd.db.bean.Member;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	int insertSelective(Member record);

	List<Member> selectAll();
}