package com.rd.db.bean;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.name
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.id
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	private Integer id;

	@Override
	public String toString() {
		return "Member [name=" + name + ", id=" + id + "]";
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.name
	 * @return  the value of member.name
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.name
	 * @param name  the value for member.name
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.id
	 * @return  the value of member.id
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.id
	 * @param id  the value for member.id
	 * @mbg.generated  Sat Mar 23 17:50:13 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}
}